spring:
  ## application name
  application:
    name: JWT-Authentication-And-Authorization
  ## Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductManagementDB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


server:
  port: 8090